# Generated by Django 5.1.5 on 2025-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_attribute_attributevalue_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['my_order'], 'verbose_name': 'image'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce/media/media/'),
        ),
    ]
